server:
  port: 8443
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/whiteproject?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true